/**
 * Baseline tests for deriveEditorPalette().
 *
 * Two layers of assertions per theme:
 *
 * 1. PASSTHROUGH — bg and fg must be identical to what the YAML contains
 *    (no derivation involved; these are taken straight from theme.colors).
 *
 * 2. REGRESSION — every derived semantic color is compared to the expected
 *    value captured when the engine was first calibrated. A tolerance of
 *    ±5 % OKLCH-lightness is allowed so minor tuning doesn't break tests,
 *    but large algorithm regressions are caught immediately.
 *
 * To re-calibrate baselines (e.g. after intentional engine changes), run:
 *   bun scripts/gen-fixtures.ts > /dev/null  # update manually
 */
import { describe, it, expect } from 'bun:test';
import { readFileSync } from 'fs';
import { join } from 'path';
import { parseThemeYAML } from '../src/theme-schema';
import { deriveEditorPalette, type EditorPalette } from '../src/theme-color-engine';
import { hexToOklch } from '../../src/engine/OklchMathEngine';

// ─── helpers ────────────────────────────────────────────────────────────────

/** Normalise hex to lowercase 7-char (#rrggbb). */
function norm(hex: string): string {
  return hex.toLowerCase().slice(0, 7);
}

/**
 * Assert two hex colours are within `maxDeltaL` on the OKLCH L axis.
 * L is in [0, 1]; maxDeltaL = 0.05 means ±5 % perceptual lightness.
 */
function expectClose(got: string, want: string, maxDeltaL = 0.05, label = '') {
  const [lg] = hexToOklch(norm(got));
  const [lw] = hexToOklch(norm(want));
  const delta = Math.abs(lg - lw);
  expect(delta).toBeLessThanOrEqual(
    maxDeltaL,
    `${label}: got ${got} (L=${lg.toFixed(3)}) vs want ${want} (L=${lw.toFixed(3)}), ΔL=${delta.toFixed(3)} > ${maxDeltaL}`,
  );
}

function loadTheme(filename: string) {
  const yaml = readFileSync(join(import.meta.dir, '../../themes', filename), 'utf8');
  return parseThemeYAML(yaml);
}

// ─── fixtures (generated by scripts/gen-fixtures.ts) ────────────────────────

const FIXTURES = [
  {
    file: 'aura-theme--aura-dark.yaml',
    label: 'Aura Dark',
    mode: 'dark',
    expected: {
      bg: '#15141B', fg: '#EDECEE',
      lineHighlight: '#27262f', selection: '#42365e',
      comment: '#6c6a70', keyword: '#805fc6',
      string: '#53c49f', fn: '#c59d6c',
      type: '#6fb1c1', cursor: '#805fc6',
    },
  },
  {
    file: 'steelbore.yaml',
    label: 'Steelbore',
    mode: 'dark',
    expected: {
      bg: '#000027', fg: '#D98E32',
      lineHighlight: '#19142c', selection: '#202c4d',
      comment: '#613d32', keyword: '#39618f',
      string: '#45bd6a', fn: '#a86c35',
      type: '#727d52', cursor: '#39618f',
    },
  },
  {
    file: 'guttenbergovitz.yaml',
    label: 'Guttenbergovitz',
    mode: 'dark',
    expected: {
      bg: '#232326', fg: '#D4BE98',
      lineHighlight: '#343130', selection: '#5b483d',
      comment: '#6c6356', keyword: '#ac7d5a',
      string: '#718868', fn: '#ab946f',
      type: '#ba92a7', cursor: '#ac7d5a',
    },
  },
  {
    file: 'the-flying-dutchman.yaml',
    label: 'The Flying Dutchman',
    mode: 'dark',
    expected: {
      bg: '#0B1119', fg: '#B0C4DE',
      lineHighlight: '#1a222b', selection: '#294154',
      comment: '#4e5968', keyword: '#4a87b0',
      string: '#398978', fn: '#af8f56',
      type: '#78a78e', cursor: '#4a87b0',
    },
  },
  {
    file: 'patina-dark.yaml',
    label: 'Patina Dark',
    mode: 'dark',
    expected: {
      bg: '#121212', fg: '#DBD7CA',
      lineHighlight: '#232423', selection: '#334346',
      comment: '#63615c', keyword: '#588b96',
      string: '#40745d', fn: '#b19e5f',
      type: '#9ea785', cursor: '#588b96',
    },
  },
  {
    file: 'compline--compline.yaml',
    label: 'Compline',
    mode: 'dark',
    expected: {
      bg: '#1A1D21', fg: '#F0EFEB',
      lineHighlight: '#2d2f33', selection: '#4a4e53',
      comment: '#707273', keyword: '#8e959c',
      string: '#919b93', fn: '#a6a190',
      type: '#b2b8b3', cursor: '#8e959c',
    },
  },
  {
    file: 'akari--akari-dawn.yaml',
    label: 'Akari Dawn (light)',
    mode: 'light',
    expected: {
      bg: '#E4DED6', fg: '#1A1816',
      lineHighlight: '#cbc6c0', selection: '#a3a4a4',
      comment: '#827e79', keyword: '#55606c',
      string: '#5e7452', fn: '#be8e60',
      type: '#3a463c', cursor: '#55606c',
    },
  },
  {
    file: 'the-flying-dutchman-high-contrast.yaml',
    label: 'The Flying Dutchman High Contrast',
    mode: 'dark',
    expected: {
      bg: '#0A1520', fg: '#FFFFFF',
      lineHighlight: '#1f2934', selection: '#334a5d',
      comment: '#6d727a', keyword: '#6796b7',
      string: '#62a081', fn: '#bca13d',
      type: '#a2c1a9', cursor: '#6796b7',
    },
  },
  {
    file: 'patina-stellar.yaml',
    label: 'Patina Stellar (light)',
    mode: 'light',
    expected: {
      bg: '#F5F2ED', fg: '#393A34',
      lineHighlight: '#dfded9', selection: '#becdce',
      comment: '#9c9b95', keyword: '#76a4b1',
      string: '#67947c', fn: '#ccb561',
      type: '#727d5f', cursor: '#76a4b1',
    },
  },
] as const;

// ─── Aura Dark quality anchors (verified against native xcode / alacritty) ──
// These are the real syntax-token colors from the official Aura Theme repo.
// They serve as *quality* assertions, tighter than the regression tolerance.
const AURA_QUALITY: Partial<Record<keyof EditorPalette, string>> = {
  keyword: '#8464C6', // purple — confirmed in aura-theme xcode + alacritty
  string:  '#54C59F', // muted green — confirmed in Aura xcode syntax keys
  fn:      '#C7A06F', // warm gold   — confirmed in Aura xcode syntax keys
  type:    '#6CB2C7', // teal        — confirmed in xcode DVT syntax keys
};

// ─── tests ──────────────────────────────────────────────────────────────────

describe('deriveEditorPalette', () => {
  for (const fixture of FIXTURES) {
    describe(fixture.label, () => {
      const theme  = loadTheme(fixture.file);
      const palette = deriveEditorPalette(theme);

      // ── mode ──────────────────────────────────────────────────────────────
      it('detects correct mode', () => {
        expect(palette.mode).toBe(fixture.mode);
      });

      // ── passthrough ───────────────────────────────────────────────────────
      it('bg passes through unchanged', () => {
        expect(norm(palette.bg)).toBe(norm(fixture.expected.bg));
      });

      it('fg passes through unchanged', () => {
        expect(norm(palette.fg)).toBe(norm(fixture.expected.fg));
      });

      // ── regression (±5 % OKLCH lightness) ───────────────────────────────
      const derived = [
        'lineHighlight', 'selection', 'comment',
        'keyword', 'string', 'fn', 'type', 'cursor',
      ] as const;

      for (const key of derived) {
        it(`${key} within 5% OKLCH lightness of baseline`, () => {
          expectClose(palette[key], fixture.expected[key], 0.05, key);
        });
      }

      // ── structural invariants ────────────────────────────────────────────
      it('lineHighlight is darker than selection', () => {
        const [lLH] = hexToOklch(palette.lineHighlight);
        const [lSel] = hexToOklch(palette.selection);
        if (fixture.mode === 'dark') {
          expect(lLH).toBeLessThan(lSel);
        } else {
          expect(lLH).toBeGreaterThan(lSel);
        }
      });

      it('keyword and string are different colors', () => {
        expect(norm(palette.keyword)).not.toBe(norm(palette.string));
      });

      it('returns all required palette keys', () => {
        const required: (keyof EditorPalette)[] = [
          'bg', 'bgAlt', 'lineHighlight', 'selection', 'selectionBorder',
          'fg', 'fgMuted', 'comment', 'cursor',
          'keyword', 'string', 'number', 'fn', 'type', 'variable', 'operator',
          'added', 'removed', 'modified',
          'error', 'warning', 'info', 'mode',
        ];
        for (const key of required) {
          expect(palette[key]).toBeDefined();
        }
      });
    });
  }

  // ── quality anchors against real Aura syntax values ───────────────────────
  describe('Aura Dark quality anchors', () => {
    const theme   = loadTheme('aura-theme--aura-dark.yaml');
    const palette = deriveEditorPalette(theme);

    for (const [key, real] of Object.entries(AURA_QUALITY) as [keyof EditorPalette, string][]) {
      it(`${key} within 3% of real Aura value (${real})`, () => {
        expectClose(palette[key] as string, real, 0.03, `aura.${key}`);
      });
    }
  });
});
