import type { ThemeYAML } from '../theme-schema';
import type { ThemeGenerator } from './base';
import { deriveEditorPalette } from '../theme-color-engine';

export const hyperGenerator: ThemeGenerator = {
  name: 'hyper',

  generate(theme: ThemeYAML): string {
    const p = deriveEditorPalette(theme);
    const c = theme.colors;
    const lines: string[] = [];

    lines.push(`// ${theme.name} — Hyper theme`);
    lines.push(`// Generated by rampa`);
    lines.push('module.exports = {');
    lines.push('  colors: {');
    lines.push(`    black: '${c.black}',`);
    lines.push(`    red: '${c.red}',`);
    lines.push(`    green: '${c.green}',`);
    lines.push(`    yellow: '${c.yellow}',`);
    lines.push(`    blue: '${c.blue}',`);
    lines.push(`    magenta: '${c.magenta}',`);
    lines.push(`    cyan: '${c.cyan}',`);
    lines.push(`    white: '${c.white}',`);
    lines.push(`    lightBlack: '${c.brightBlack}',`);
    lines.push(`    lightRed: '${c.brightRed}',`);
    lines.push(`    lightGreen: '${c.brightGreen}',`);
    lines.push(`    lightYellow: '${c.brightYellow}',`);
    lines.push(`    lightBlue: '${c.brightBlue}',`);
    lines.push(`    lightMagenta: '${c.brightMagenta}',`);
    lines.push(`    lightCyan: '${c.brightCyan}',`);
    lines.push(`    lightWhite: '${c.brightWhite}',`);
    lines.push('  },');
    lines.push(`  backgroundColor: '${c.bg}',`);
    lines.push(`  foregroundColor: '${c.fg}',`);
    lines.push(`  cursorColor: '${p.cursor}',`);
    lines.push(`  selectionColor: '${p.selection}80',`);
    lines.push('};');

    return lines.join('\n') + '\n';
  },

  installPath(os) {
    if (os === 'darwin' || os === 'linux') return '~/.hyper_plugins/local';
    if (os === 'win32') return '%APPDATA%\\Hyper\\.hyper_plugins\\local';
    return null;
  },

  fileExtension() {
    return '.js';
  },
};
